- name: Get Cisco ASA NTP Status
  import_role:
    name: config_ntp
    tasks_from: asa
  check_mode: true

- name: Set ASA Compliance Facts
  set_fact:
    problem_description: "The following changes need to be made:\n\n***********************\n{{ asa_result.updates | join('\n') }}\n***********************"
    short_description: "{{ inventory_hostname | upper }} ntp configuration out of compliance"
    ntp_compliant: "No"
  when: (ansible_network_os == 'asa' and asa_result.changed)

- name: Create SNOW Problem Ticket
  include_tasks:
    file: snow_ticket.yml
  when: asa_result.changed

- name: Update SNOW CMDB
  include_tasks:
    file: snow_cmdb.yml
