- name: Update Netbox Device Information
  netbox.netbox.netbox_device:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ hostvars[item].inventory_hostname }}"
      serial: "{{ hostvars[item].ansible_net_serialnum | default('') }}"
      custom_fields:
        device_version: "{{ hostvars[item].ansible_net_version | default('') }}"
    state: present
  loop: "{{ groups['all'] }}"
  delegate_to: localhost
  run_once: true
