- name: Configure PanOS DNS Servers
  paloaltonetworks.panos.panos_mgtconfig:
    provider: "{{ provider }}"
    dns_server_primary: "{{ dns_servers[0] }}"
    dns_server_secondary: "{{ dns_servers[1] }}"
  delegate_to: localhost
