name: Main Workflow

on:
  push:
    branches:
      - '*'
    except:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Ansible Lint
        run: |
          ansible-playbook lint.yml
